### ISSUE TITLE
HTTP 500 during faktury.mzcr.cz REST API unavailability

### ISSUE THREAD

**Issue by shaddeus** [Listonoh/django-restapi-test#1]
I get HTTP 500 from all pages if the REST API faktury.mzcr.cz is unavailable.

**Comment by Listonoh** [comment]
I tested it locally and it works. Try just this link if it is not something else: https://faktury.mzcr.cz/rest/organizations/?page=1&per-page=5

If the link works then there is something broken in this app...

**Comment by shaddeus** [comment]
Try refresh the page without the Internet connection. I don't care about CSS.

**Comment by Listonoh** [comment]
Oh i get it now :D

**Comment by Listonoh** [comment]
resolved by adding decorator that handles exceptions from request
