### ISSUE TITLE
Query parameter per-page disappeared

### ISSUE THREAD

**Issue by shaddeus** [Listonoh/django-restapi-test#5]
The query string parameter `per-page` disappeared if is set and I use a paging at the bottom of page.

**Comment by Listonoh** [comment]
I do not know how to deal with it correctly.
The first thing, that came to my mind is to just append it after "href" in every link if it is set...
Or by creating some token for instance...

**Comment by shaddeus** [comment]
Token for instance? Do you mean saving a per-page parameter into session data? What will happen if I have two or more browser tabs and each with different `per-page` option?

**Comment by Listonoh** [comment]
Yea creating a session would set ```per-page``` for a given browser... 
so I went with a variable in the `context` that holds the value and if it is not set the `per_page` is 5.
It is not ideal because I had to copy one piece of code to 3 locations (in `index.html`) ... but it works

**Comment by shaddeus** [comment]
I'm suprised with `firstof` [usage](https://github.com/Listonoh/django-restapi-test/blob/master/mysite/catalog/templates/catalog/index.html#L30). Why did you use `firstof` built in template tag there?

How you can refactor the duplicity code?

**Comment by Listonoh** [comment]
I thought about creating a variable in the template with `set` but it did not work so I went with another method.
There was the possibility of introducing the variable with `with(...):` but that is more unreadable, I think.

**Comment by shaddeus** [comment]
What about [`include`](https://docs.djangoproject.com/en/3.2/ref/templates/builtins/#include) a list item `<li>...</li>` with anchor?

**Comment by Listonoh** [comment]
Hmm, I do not think I understand it clearly. 
like: 
```jinja
{% for page in pages %}
  {% include part_of_nav with page_number=page active=true .... %}
{% endfor %}
```

or create a list of pages (strings starting with <li>...) with every information in `views.py` that is needed and then just render it?

or leave as it is now and there would be always `per_page` in the query.

**Comment by shaddeus** [comment]
In my opinion the `per_page` in each query is OK. Yes, Django template for-cycle and `include`. It would be a nice solution.

**Comment by Listonoh** [comment]
So what now? :D

**Comment by shaddeus** [comment]
The work is not done when the code starts working, but only when it is correct. :slightly_smiling_face: 

Let implement the suggested solution
```django
{% for page in pages %}
  {% include part_of_nav with page_number=page active=true .... %}
{% endfor %}
```

**Comment by Listonoh** [comment]
Implemented took me a while to add one inside of `include` but `|add:1` makes it.

**Comment by shaddeus** [comment]
I see some plain `&per-page=` on web page. But it does not matter. Good job!
